// <auto-generated />
using System;
using CervezaMin_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CervezaMin_API.Migrations
{
    [DbContext(typeof(CervezaContext))]
    [Migration("20240401221701_mandc")]
    partial class mandc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CervezaMin_API.Models.Cerveza", b =>
                {
                    b.Property<int>("IdCerveza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCerveza"));

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCerveza");

                    b.HasIndex("IdMarca");

                    b.ToTable("Cervezas");

                    b.HasData(
                        new
                        {
                            IdCerveza = 1,
                            EsActivo = true,
                            FechaActualizacion = new DateTime(2024, 4, 1, 17, 17, 1, 345, DateTimeKind.Local).AddTicks(580),
                            FechaCreacion = new DateTime(2024, 4, 1, 17, 17, 1, 345, DateTimeKind.Local).AddTicks(579),
                            IdMarca = 1,
                            Nombre = "Cusqueña Dorada",
                            NombreImagen = "CusqueñaDorada",
                            Precio = 12.0,
                            Stock = 1,
                            UrlImagen = "https://srv.com/cervezasMin/cusqueñaDorada.webp"
                        },
                        new
                        {
                            IdCerveza = 2,
                            EsActivo = true,
                            FechaActualizacion = new DateTime(2024, 4, 1, 17, 17, 1, 345, DateTimeKind.Local).AddTicks(585),
                            FechaCreacion = new DateTime(2024, 4, 1, 17, 17, 1, 345, DateTimeKind.Local).AddTicks(584),
                            IdMarca = 1,
                            Nombre = "Cusqueña Negra",
                            NombreImagen = "CusqueñaNegra",
                            Precio = 15.0,
                            Stock = 1,
                            UrlImagen = "https://srv.com/cervezasMin/cusqueñaNegra.webp"
                        },
                        new
                        {
                            IdCerveza = 3,
                            EsActivo = true,
                            FechaActualizacion = new DateTime(2024, 4, 1, 17, 17, 1, 345, DateTimeKind.Local).AddTicks(588),
                            FechaCreacion = new DateTime(2024, 4, 1, 17, 17, 1, 345, DateTimeKind.Local).AddTicks(588),
                            IdMarca = 1,
                            Nombre = "Cusqueña Trigo",
                            NombreImagen = "CusqueñaTrigo",
                            Precio = 15.0,
                            Stock = 1,
                            UrlImagen = "https://srv.com/cervezasMin/cusqueñaTrigo.webp"
                        },
                        new
                        {
                            IdCerveza = 4,
                            EsActivo = true,
                            FechaActualizacion = new DateTime(2024, 4, 1, 17, 17, 1, 345, DateTimeKind.Local).AddTicks(592),
                            FechaCreacion = new DateTime(2024, 4, 1, 17, 17, 1, 345, DateTimeKind.Local).AddTicks(591),
                            IdMarca = 2,
                            Nombre = "Cristal Rubia",
                            NombreImagen = "CristalRubia",
                            Precio = 15.0,
                            Stock = 1,
                            UrlImagen = "https://srv.com/cervezasMin/cristalrubia.webp"
                        },
                        new
                        {
                            IdCerveza = 5,
                            EsActivo = true,
                            FechaActualizacion = new DateTime(2024, 4, 1, 17, 17, 1, 345, DateTimeKind.Local).AddTicks(596),
                            FechaCreacion = new DateTime(2024, 4, 1, 17, 17, 1, 345, DateTimeKind.Local).AddTicks(594),
                            IdMarca = 3,
                            Nombre = "Pilsen Callao",
                            NombreImagen = "Pilsen Callao",
                            Precio = 15.0,
                            Stock = 1,
                            UrlImagen = "https://srv.com/cervezasMin/pilsenCallao.webp"
                        });
                });

            modelBuilder.Entity("CervezaMin_API.Models.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarca"));

                    b.Property<string>("Empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMarca");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            IdMarca = 1,
                            Empresa = "AB InBev",
                            FechaActualizacion = new DateTime(2024, 4, 1, 17, 17, 1, 345, DateTimeKind.Local).AddTicks(404),
                            FechaCreacion = new DateTime(2024, 4, 1, 17, 17, 1, 345, DateTimeKind.Local).AddTicks(390),
                            Nombre = "Cusqueña"
                        },
                        new
                        {
                            IdMarca = 2,
                            Empresa = "Backus",
                            FechaActualizacion = new DateTime(2024, 4, 1, 17, 17, 1, 345, DateTimeKind.Local).AddTicks(408),
                            FechaCreacion = new DateTime(2024, 4, 1, 17, 17, 1, 345, DateTimeKind.Local).AddTicks(407),
                            Nombre = "Cristal"
                        },
                        new
                        {
                            IdMarca = 3,
                            Empresa = "Backus",
                            FechaActualizacion = new DateTime(2024, 4, 1, 17, 17, 1, 345, DateTimeKind.Local).AddTicks(411),
                            FechaCreacion = new DateTime(2024, 4, 1, 17, 17, 1, 345, DateTimeKind.Local).AddTicks(410),
                            Nombre = "Pilsen callao"
                        });
                });

            modelBuilder.Entity("CervezaMin_API.Models.Cerveza", b =>
                {
                    b.HasOne("CervezaMin_API.Models.Marca", "MarcaNavegacion")
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarcaNavegacion");
                });
#pragma warning restore 612, 618
        }
    }
}
